### ISSUE TITLE
"Upgrade" form nits (add help tooltips/labels)

### ISSUE THREAD

**Issue by cvan** [Pinecast/pinecast#103]
<img src="https://cloud.githubusercontent.com/assets/203725/18659662/d666a7e4-7ec0-11e6-8337-da8310109dcc.png" width="50%">

* If there are only two steps, consider removing the step progress line (or enumerate the dots); as is, it looks awkward and confusing
* I know [Stripe](https://frend.co/components/tooltip/) says `CVC`, but IME I've seen `CVV` (or `CV2`) more often
* Add tooltip/help text for `CV2` (consider using [this awesome vanilla JS tooltip lib](https://frend.co/components/tooltip/))
* Consider removing `Card Holder` (is this actually required? I know Stripe doesn't require this, so I don't think it's required)
* Rename `Card Holder` to `Name on Card` possibly?
* Change `Month` field from `input[type=text]` to `input[type=range]`
* Add to `Month` field `maxlength="2" min="1" max="12"` (curious how this works with i10n; I assume Arabic numerals for CCs are universal, but I don't know)
* Change `Year` field from `input[type=text]` to `input[type=range]` (consider adding a `pattern` that requires the card to be equal to or greater than the current year)

**Comment by mattbasta** [comment]
- Any fields that seem like they shouldn't be required are there because it makes it easier to deal with fraud, and most password managers are good.
- Month/Year need to stay `[type=text]` to be friendly with some weird password managers. I've had a world of trouble.
- Arabic numerals aren't supported by Stripe anyway, IIRC, so that's moot.
- I considered adding a tooltip for CVC but honestly if you don't know what that is by now, how have you used the internet. On mobile, Chrome will auto-fill it. And frankly the tooltip is unhelpful if you don't know what your CVC is, since it's in different places for many card types. Fuck American Express.
- "CVV" alone isn't actually used by any credit cards to describe the number. "CVC" matches the docs that I link folks to when they have trouble, so I'm going to stick with that.

**Comment by cvan** [comment]
> Arabic numerals aren't supported by Stripe anyway, IIRC, so that's moot.

> Arabic numerals, also called Hindu-Arabic or Hindu numerals, are the ten digits: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9.

**Comment by cvan** [comment]
what about at least renamnig `Card Holder` to `Card Holder Name` to be consistent with the labels for the bank info. fields?

**Comment by mattbasta** [comment]
The card holder name field is already changed, but I need to bump the versions of the packages on NPM and I'd rather not do that until I have other changes that need to go out. It's a real production.

**Comment by cvan** [comment]
> It's a real production.

So don't give it the production-quality treatment 👑 👍
