### ISSUE TITLE
"Settings" page takes a long time to load for the first time

### ISSUE THREAD

**Issue by cvan** [Pinecast/pinecast#104]
I don't have the numbers, but loading [the "Settings" page](https://pinecast.com/accounts/settings) took a good few seconds to load for the first time.

**Comment by mattbasta** [comment]
It's probably because it has to load both the credit card form as well as the bank details form, and it has to hit Stripe to get your CC/bank summary if you've added them, which can be tenuous at best.

There's no memcached/Redis set up in front of the DB, so it should be consistently slow. It might have just been CF farting a lil bit or something. The much lower-hanging fruit would be to concatenate the CSS files, but even that is a pretty small optimization thanks to HTTP/2.

Feel free to reopen if the latency is egregious, but if it's consistently under ~3s, I'm okay with that.
