### ISSUE TITLE
Is there any way to use to use a Stripe UI for the "Connect" payment options on the "Account Settings" page

### ISSUE THREAD

**Issue by cvan** [Pinecast/pinecast#112]
As a user of Stripe, I feel safe and comfortable when I see the [Stripe Checkout](https://stripe.com/checkout) modal. I'm not very familiar with Stripe Connect; is there any way to provide a similar UI? I feel it'd give users more peace of mind, especially considering you're asking for bank information and the last four SSN digits.

**Comment by mattbasta** [comment]
Stripe Connect is only the back-end piece. I built a custom UI because the Checkout modal is a bit jarring, and in validating it with users, they felt a bit freaked out at what felt like an out-of-place UI. There's no way to make the modal styles match the app, IIRC. It's also an extra click, because you have to open the modal, which isn't amazing.

Consider the tip jar. Users need to add a card, but then also choose a tip amount. Having a modal just to add card info but not for the rest of the flow makes the experience really disjoint.

**Comment by mattbasta** [comment]
Also, I don't think Checkout works with managed accounts, which is what powers tip jar payouts, so the bank details form couldn't be migrated.

**Comment by mattbasta** [comment]
I looked into this and it really isn't feasible without switching to a checkout button, which doesn't really suit the use case well. It also doesn't work for connected accounts.

I'll reopen if something becomes available, or if I figure out something clever.

**Comment by cvan** [comment]
> Consider the tip jar. Users need to add a card, but then also choose a tip amount. Having a modal just to add card info but not for the rest of the flow makes the experience really disjoint.

idk, I'd trust Stripe (and it already remembers my data with a cookie or by my entering my phone number) over some random startup with my personal info, esp. bank info.

**Comment by mattbasta** [comment]
There's literally no UI that Stripe provides for bank info, just credit card info.

**Comment by cvan** [comment]
Yeah, I figured. They should fix that.
