### ISSUE TITLE
Explicit checkbox per episode instead of on podcast

### ISSUE THREAD

**Issue by abts-doug** [Pinecast/pinecast#78]
Currently you can set your podcast to explicit in the settings. A simple checkbox. We need to move that functionality to address individual episodes so that users can designate which episodes are explicit.

**Comment by mattbasta** [comment]
I was going to implement this today, but it begs the question of what it should do. The iTunes RSS spec says that it can go on either the whole podcast or individual items:

http://www.apple.com/itunes/podcasts/specs.html

Placed on the podcast and set to "yes", it shows every episode as explicit:

![screen shot 2015-11-30 at 11 10 58 pm](https://cloud.githubusercontent.com/assets/279498/11494484/aadca39e-97b7-11e5-933f-0417b26bfbef.png)

While that's fine, the documentation doesn't say what happens if it's set to "yes" on the show as well as the individual episodes. Presumably nothing. Should it even still be shown, then? Probably not.

Curiously, it can also be set to "clean", which shows a little "clean" badge (I couldn't find a podcast to screenshot). It's unclear whether a podcast with "yes" set and an episode with "clean" set cancel each other out, or whether you get a little clean island inside an explicit ocean.

I'm definitely not implementing the "clean" flag, since that's a weird third option and the UX around it is questionable at best. I'm going to have to sleep on the options around having a per-episode explicit flag and how to expose that under different circumstances.
